#!/usr/bin/env node
/**
 * Poll Wessex Water's near real-time storm overflow feed, keep a local history
 * for the overflows around Frome, and export JSON for the page.
 *
 *   node poll.js
 *
 * No API key. No dependencies. Node 24 has node:sqlite and fetch built in.
 */

import { DatabaseSync } from 'node:sqlite';
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { DAY, fmtDuration, spillMs } from './docs/lib/format.js';

// --- Configuration ---------------------------------------------------------

const API =
  'https://services.arcgis.com/3SZ6e0uCvPROr4mS/arcgis/rest/services/' +
  'Wessex_Water_Storm_Overflow_Activity/FeatureServer/0/query';

const PAGE_SIZE = 2000; // Wessex's documented per-request ceiling

// Frome town centre. Keep in step with CENTRE in scripts/build-basemap.js.
const CENTRE = { lat: 51.2308, lon: -2.3208 };

// The monitor set is a fixed, hand-curated list of Wessex `Id`s — the map crop
// and the whole design assume this exact set. It was generated by the fallback
// rule below; re-run `node scripts/audit-ids.js` now and then to see what Wessex
// have added or retagged, then edit this list by hand. Add/remove freely.
const PIN_TO_IDS = [
  'WXW00051',  // RIVER FROME VIA SWS
  'WXW00062',  // RIVER FROME (VIA SWS)
  'WXW00120',  // RIVER FROME
  'WXW00307',  // MELLS RIVER
  'WXW00308',  // MELLS RIVER
  'WXW00333',  // RIVER FROME
  'WXW00340',  // WHATLEY BROOK
  'WXW00369',  // RODDEN BROOK
  'WXW00401',  // MELLS RIVER (S)
  'WXW00402',  // MELLS RIVER (S)
  'WXW00420',  // ADDERWELL BROOK
  'WXW00453',  // RIVER FROME(S)
  'WXW00454',  // RIVER FROME(S)
  'WXW00490',  // MELLS STREAM(S)
  'WXW00596',  // MELLS STREAM
  'WXW00654',  // TRIB OF RIVER FROME (VIA SWS)
  'WXW00693',  // TRIBUTARY OF NUNNEY BROOK
  'WXW00709',  // MELLS STREAM(S)
  'WXW00710',  // MELLS STREAM
  'WXW00711',  // RIVER FROME (VIA SWS)
  'WXW00788',  // RIVER FROME
  'WXW00805',  // RIVER FROME
  'WXW00816',  // NUNNEY BROOK
  'WXW00818',  // MELLS STREAM
  'WXW00880',  // RIVER FROME
  'WXW00934',  // RIVER FROME (VIA SWS)
  'WXW00935',  // TRIB OF THE RIVER FROME
  'WXW00936',  // SOMERSET FROME(S)
  'WXW00979',  // RIVER FROME
  'WXW01068',  // TRIB OF MELLS STREAM
  'WXW01156',  // TRIBUTARY OF RIVER FROME
  'WXW01185',  // RIVER FROME
  'WXW01187',  // TRIB OF THE NUNNEY BROOK(S)
  'WXW01242',  // RIVER FROME
  'WXW01243',  // TRIBUTARY OF RIVER FROME
  'WXW01245',  // RIVER FROME VIA SWS
  'WXW01272',  // RIVER FROME
  'WXW01297',  // RIVER FROME
];

// Fallback rule, used only when PIN_TO_IDS is empty and by scripts/audit-ids.js.
// A row is kept if it is within RADIUS_KM of CENTRE, or within CATCHMENT_KM and
// its receiving watercourse name contains one of WATERCOURSES. The outer bound
// matters: the *Bristol* Frome (a different river) starts ~31 km out, and Wessex
// also supply the Dorset Frome further still. The real Frome-system monitors all
// sit inside ~15 km, so 30 has a clean margin.
const RADIUS_KM = 7;
const CATCHMENT_KM = 30;
const WATERCOURSES = [
  'frome', 'mells', 'adderwell', 'nunney brook', 'rodden brook', 'whatley brook',
  'maiden bradley brook', 'marston brook', 'redford water', 'henhambridge brook',
];

const EXPORT_DAYS = 90;

const ROOT = dirname(fileURLToPath(import.meta.url));
const DB_PATH = join(ROOT, 'overflows.db');
const JSON_PATH = join(ROOT, 'docs', 'data.json');

// --- Database --------------------------------------------------------------

const SCHEMA = `
CREATE TABLE IF NOT EXISTS monitors (
  id           TEXT PRIMARY KEY,
  label        TEXT,            -- your name for it; the poller never overwrites this
  latitude     REAL,
  longitude    REAL,
  watercourse  TEXT,
  first_seen   INTEGER,
  last_seen    INTEGER
);

CREATE TABLE IF NOT EXISTS events (
  monitor_id   TEXT NOT NULL,
  start_ms     INTEGER NOT NULL,
  end_ms       INTEGER,         -- NULL while ongoing
  PRIMARY KEY (monitor_id, start_ms)
);

CREATE TABLE IF NOT EXISTS snapshots (
  polled_at       INTEGER NOT NULL,
  monitor_id      TEXT NOT NULL,
  status          INTEGER,
  latest_start_ms INTEGER,
  latest_end_ms   INTEGER,
  PRIMARY KEY (polled_at, monitor_id)
);

CREATE INDEX IF NOT EXISTS idx_events_start ON events (start_ms);
`;

/** node:sqlite rejects `undefined`, which ArcGIS hands us for absent fields. */
const val = (x) => (x === undefined ? null : x);

// --- Fetching --------------------------------------------------------------

async function fetchAll() {
  const rows = [];
  for (let offset = 0; ; offset += PAGE_SIZE) {
    const params = new URLSearchParams({
      where: '1=1',
      outFields: '*',
      returnGeometry: 'false',
      f: 'json',
      resultOffset: String(offset),
      resultRecordCount: String(PAGE_SIZE),
    });

    const response = await fetch(`${API}?${params}`, {
      signal: AbortSignal.timeout(60_000),
      headers: { accept: 'application/json' },
    });
    if (!response.ok) throw new Error(`Wessex feed returned ${response.status}`);

    const body = await response.json();
    // ArcGIS reports failures with HTTP 200 and an error object.
    if (body.error) throw new Error(`Wessex feed: ${body.error.message}`);

    const page = (body.features ?? []).map((f) => f.attributes);
    rows.push(...page);

    if (page.length < PAGE_SIZE || !body.exceededTransferLimit) return rows;
  }
}

function haversineKm(a, b) {
  const R = 6371;
  const rad = (d) => (d * Math.PI) / 180;
  const dLat = rad(b.lat - a.lat);
  const dLon = rad(b.lon - a.lon);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/** The geography + watercourse-name rule. Also used by scripts/audit-ids.js. */
function matchesRule(row) {
  const { Latitude: lat, Longitude: lon } = row;
  if (lat == null || lon == null) return false;
  const km = haversineKm(CENTRE, { lat, lon });
  if (km <= RADIUS_KM) return true;
  const wc = (row.ReceivingWaterCourse ?? '').toLowerCase();
  return km <= CATCHMENT_KM && WATERCOURSES.some((n) => wc.includes(n));
}

function isLocal(row) {
  if (PIN_TO_IDS.length > 0) return PIN_TO_IDS.includes(String(row.Id));
  return matchesRule(row);
}

// --- Storing ---------------------------------------------------------------

/**
 * Wessex give us the latest event's start and end directly, so an event is
 * identified by (monitor, start). Seeing the same start again just fills in the
 * end time; a start we haven't seen before is a new spill.
 */
function store(db, rows, polledAt) {
  const upsertMonitor = db.prepare(`
    INSERT INTO monitors (id, latitude, longitude, watercourse, first_seen, last_seen)
    VALUES (?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
      latitude = excluded.latitude,
      longitude = excluded.longitude,
      watercourse = excluded.watercourse,
      last_seen = excluded.last_seen`);

  const recordSnapshot = db.prepare(`
    INSERT OR REPLACE INTO snapshots
      (polled_at, monitor_id, status, latest_start_ms, latest_end_ms)
    VALUES (?, ?, ?, ?, ?)`);

  const seenEvent = db.prepare(
    'SELECT 1 AS found FROM events WHERE monitor_id = ? AND start_ms = ?');

  const upsertEvent = db.prepare(`
    INSERT INTO events (monitor_id, start_ms, end_ms) VALUES (?, ?, ?)
    ON CONFLICT(monitor_id, start_ms) DO UPDATE SET
      end_ms = COALESCE(excluded.end_ms, events.end_ms)`);

  let fresh = 0;

  db.exec('BEGIN');
  try {
    for (const row of rows) {
      const id = String(row.Id);

      upsertMonitor.run(
        id, val(row.Latitude), val(row.Longitude),
        row.ReceivingWaterCourse ?? 'Unknown', polledAt, polledAt);

      recordSnapshot.run(
        polledAt, id, val(row.Status),
        val(row.LatestEventStart), val(row.LatestEventEnd));

      const start = row.LatestEventStart;
      if (start == null) continue;

      // While it's still discharging the reported end belongs to a previous
      // event, so leave the end open until the status clears.
      const end = row.Status === 1 ? null : val(row.LatestEventEnd);

      if (!seenEvent.get(id, start)) fresh += 1;
      upsertEvent.run(id, start, end);
    }
    db.exec('COMMIT');
  } catch (error) {
    db.exec('ROLLBACK');
    throw error;
  }

  return fresh;
}

// --- Exporting -------------------------------------------------------------

async function exportJson(db, rows, polledAt) {
  const liveStatus = new Map(rows.map((r) => [String(r.Id), r.Status]));
  const cutoff = polledAt - EXPORT_DAYS * DAY;

  const eventsFor = db.prepare(`
    SELECT start_ms, end_ms FROM events
    WHERE monitor_id = ? AND start_ms >= ?
    ORDER BY start_ms`);

  // Only publish monitors the filter has matched recently. A monitor that drops
  // out — because you narrowed the catchment, or Wessex stopped listing it —
  // ages off the page after a week but keeps its history in the database.
  const monitors = db
    .prepare(`SELECT id, label, latitude, longitude, watercourse, first_seen FROM monitors
              WHERE last_seen >= ? ORDER BY id`)
    .all(polledAt - 7 * DAY)
    .map((m) => ({
      id: m.id,
      label: m.label ?? m.id,
      lat: m.latitude,
      lon: m.longitude,
      watercourse: m.watercourse,
      since: m.first_seen,
      status: liveStatus.get(m.id) ?? null,
      events: eventsFor.all(m.id, cutoff)
        .map((e) => ({ start: e.start_ms, end: e.end_ms })),
    }));

  await mkdir(dirname(JSON_PATH), { recursive: true });
  await writeFile(
    JSON_PATH,
    JSON.stringify(
      { polled_at: polledAt, window_days: EXPORT_DAYS, place: 'Frome', monitors },
      null, 1) + '\n');

  return monitors.length;
}

// --- Entry point -----------------------------------------------------------

async function main() {
  const polledAt = Date.now();

  console.log('Fetching Wessex Water storm overflow feed…');
  const all = await fetchAll();
  const local = all.filter(isLocal);
  console.log(`  ${all.length} overflows region-wide, ${local.length} near Frome`);

  if (local.length === 0) {
    console.error('  Nothing matched. Widen RADIUS_KM, or check the field names.');
    process.exitCode = 1;
    return;
  }

  const db = new DatabaseSync(DB_PATH);
  db.exec(SCHEMA);

  const fresh = store(db, local, polledAt);
  const count = await exportJson(db, local, polledAt);
  db.close();

  const discharging = local.filter((r) => r.Status === 1);
  const offline = local.filter((r) => r.Status === -1).length;
  const ongoing = discharging
    .map((r) => spillMs({ start: r.LatestEventStart, end: null }, polledAt))
    .filter(Number.isFinite);

  console.log(
    `  ${discharging.length} discharging` +
    (ongoing.length ? ` (longest running ${fmtDuration(Math.max(...ongoing))})` : '') +
    `, ${offline} offline, ${fresh} new spill${fresh === 1 ? '' : 's'} recorded`);
  console.log(`  wrote docs/data.json (${count} monitors)`);
}

// Run the poll only when executed directly; scripts/audit-ids.js imports the
// pieces below without triggering a poll.
if (process.argv[1] === import.meta.filename) {
  main().catch((error) => {
    console.error(`Poll failed: ${error.message}`);
    process.exitCode = 1;
  });
}

export { fetchAll, matchesRule, haversineKm, CENTRE, RADIUS_KM, CATCHMENT_KM, WATERCOURSES, PIN_TO_IDS };
